#log_type error
#log_type warning
#log_type notice
#log_type information
log_type debug

log_dest file /mosquitto/log/mosquitto.log
log_timestamp true
log_timestamp_format %Y-%m-%dT%H:%M:%S

persistence false
persistence_location /mosquitto/data/

allow_anonymous false
#allow_zero_length_clientid false
#auth_plugin_deny_special_chars true

password_file /mosquitto/config/passwd.txt
acl_file /mosquitto/config/acls
listener 1883
